### ISSUE TITLE
OutOfMemoryError

### ISSUE THREAD

**Issue by boczkas** [Hoymm/XO#27]
Wprowadź imię gracza dla symbolu X :
l
Kto powinien zaczynać pierwszy? Wpisz symbol gracza ([O] or [X]): 
O
Ile symboli w nieprzerwanej linii aby wygrać rundę? : 
5
Wprowadź szerokość tablicy:
123456789
Wprowadź wysokość tablicy:
123456789
l [O]: 0 	 l [X]: 0

x
0
12
45
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at java.base/java.util.Arrays.copyOf(Arrays.java:3744)
	at java.base/java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:146)
	at java.base/java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:512)
	at java.base/java.lang.StringBuilder.append(StringBuilder.java:141)
	at Data.BoardController.toString(BoardController.java:20)
	at Data.Data.gameBoardDisplayInfo(Data.java:52)
	at GameState.Game.displayGame(Game.java:17)
	at XOGame.runGame(XOGame.java:28)
	at Main.main(Main.java:4)

**Comment by Hoymm** [comment]
Naprawione
