### ISSUE TITLE
Duża liczba go przekręca

### ISSUE THREAD

**Issue by boczkas** [Hoymm/XO#28]
Gra z niestandardowymi ustawieniami [c] lub szybka [d]:
c
Wybrałeś gre z niestandardowymi ustawieniami.
Wprowadź imię gracza dla symbolu O :
3
Imię powinno zawierać jedynie litery. "3" jest nieakceptowalne.
Wprowadź imię gracza dla symbolu O :
a
Wprowadź imię gracza dla symbolu X :
a
Kto powinien zaczynać pierwszy? Wpisz symbol gracza ([O] or [X]): 
O
Ile symboli w nieprzerwanej linii aby wygrać rundę? : 
3
Wprowadź szerokość tablicy:
123456789
Wprowadź wysokość tablicy:
1234785685248247
Exception in thread "main" java.lang.NumberFormatException: For input string: "1234785685248247"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.base/java.lang.Integer.parseInt(Integer.java:652)
	at java.base/java.lang.Integer.valueOf(Integer.java:983)
	at GameState.UserIO.InputParamsValidator.isTableParamVaild(InputParamsValidator.java:11)
	at GameState.UserIO.InputParams.insertAndValidateTableParam(InputParams.java:62)
	at GameState.UserIO.InputParams.getPlayerNamesAndBoardDataFromUser(InputParams.java:31)
	at GameState.StartGameState.tryFetchAndProcessValidInputFromUser(StartGameState.java:17)
	at XOGame.runGame(XOGame.java:26)
	at Main.main(Main.java:4)

**Comment by Hoymm** [comment]
Ustawione na przedział min 3, max 50
